### ISSUE TITLE
Unable to retain login of newly migrated account

### ISSUE THREAD

**Issue by walkersgaming** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#40] opened 2021-08-28 16:10 UTC
**Describe the bug**
I migrated one of my accounts to Microsoft, since doing so when I add it using the beta feature it isn't saved and has to be readded every time I launch my client.

**To Reproduce**
Steps to reproduce the behaviour:
1. Migrate account being used in account switcher
2. Remove account from account switcher
3. Re-add with beta Microsoft account feature
4. Login
5. Close Minecraft
6. Reopen Minecraft
7. Open account switcher, account missing

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.16.4
 - Mod Version: 7.1.1
 - Loader type: Fabric
 - Loader version: 0.11.6
 - (Fabric only) Fabric API: 0.39.2 1.16

**Comment by Tomcatchriss** [comment] 2021-08-29 11:55
Yes, I have the same problem.

Additional Information: If you try to re-add the accounts, yout get a message from Microsoft, that this account has violate against the terms of use of Microsoft. This is a big issue!

**Comment by VidTuGit** [comment] 2021-09-14 13:43
I'm unable to reproduce this issue. What OS are you using?

**Comment by Tomcatchriss** [comment] 2021-09-14 13:52
I'm using Windows 10. And for me this problem could be reproduced with ar least 2 accounts migrated. Add them to the Switcher, switch a few times between the accounts, not knowing exactly if an account was involved that was not migrated. I vote everyday for the server i'm playing on with some of my accounts.

The first day i'm added my accounts was fine, the next day, 3 of 3 accounts was blocked.

**Comment by VidTuGit** [comment] 2021-09-14 15:04
Hmm, I currently do not have 2+ migrated accounts to test that issue.
When using one (single) account there are no problems for me. (saving/logging in works, everything is just fine)

**Comment by LordTenebris17** [comment] 2021-09-15 15:26
Hey i have the exactly same issue mod is not collecting the microsoft account data i believe ? im using fabric 1.16.5 and that whats happening when i add a microsoft account and when i reopened the minecraft its just going away and i have to login again.

**Comment by VidTuGit** [comment] 2021-09-15 17:31
Does it log some errors on adding an account or/and closing accounts GUI?

**Comment by LordTenebris17** [comment] 2021-09-16 17:14
> Does it log some errors on adding an account or/and closing accounts GUI?

No im not seeing a error message unfortunately but the things is i dont know how did i do that but i have a microsoft account which is logged in and not removing when i close but the other accounts getting removed somehow

**Comment by LordTenebris17** [comment] 2021-09-17 14:38
also checked logs but cant really see a error because of that should is end you the logs file if you believe you can see it ?

**Comment by LordTenebris17** [comment] 2021-09-19 18:40
is there any uptades about the bug its really annoying to always add the accounts over and over

**Comment by VidTuGit** [comment] 2021-09-20 13:05
There's only one update: I can't reproduce it

**Comment by VidTuGit** [comment] 2021-09-20 16:19
> 
> 
> Looks like it's to do with adding more than one, removed all accounts, added the first Microsoft account (which didn't work previously) and it worked, then when I tried adding a second Microsoft account it doesn't retain it

![image](https://user-images.githubusercontent.com/60929459/134037408-99771421-98ca-41d2-9c5d-1bbf304eaa6a.png)
I found the cause. Will be fixed in 7.1.2.

**Comment by LordTenebris17** [comment] 2021-09-20 16:29
YES THANKS ! uhm estimated when is it going to be realize if its not a secret :D

**Comment by VidTuGit** [comment] 2021-09-20 17:23
This bug is fixed. I'm about to implement #36 and release a new version.

**Comment by LordTenebris17** [comment] 2021-09-20 17:25
okay thanks a lot !

**Comment by VidTuGit** [comment] 2021-09-20 17:39
> 
> 
> okay thanks a lot !

Nope, I won't implement these button movements (36), this requires a total rewriting of the account storage system.

**Comment by LordTenebris17** [comment] 2021-09-20 17:41
yeah i meant thanks for fixing this annoying bug :D

**Comment by VidTuGit** [comment] 2021-09-20 22:52
> 
> 
> yeah i meant thanks for fixing this annoying bug :D

This bug should be fixed in the new [7.1.2](https://modrinth.com/mod/in-game-account-switcher) release.


@walkersgaming, your issue should be fixed now too. If not, create a new issue and/or [join Discord](https://discord.gg/vq4DYbHtP2) for helping me with fixing this bug.

**Closed by VidTuGit** 2021-09-20 22:52 UTC
Labels: bug
