### ISSUE TITLE
ClassNotFoundException Crash during game launch

### ISSUE THREAD

**Issue by yoshiyoshyosh** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#38] opened 2021-08-18 23:41 UTC
The game crashes during mixin before the window launches, throwing a MixinTransformerError due to a ClassNotFoundException. a crash report is not generated.
This crash occurs only when I enable this mod, and I only had Fabric API, Mod Menu, and this mod enabled for the provided log below.

**Log**
https://gist.github.com/yoshiyoshyosh/0465357bbd0fd01cf1720240c589c3d3

**Versions:**
 - Minecraft: 1.17.1
 - Java: 16.0.1 (AdoptOpenJDK)
 - Mod Version: 7.1.0
 - Loader type: Fabric
 - Loader version 0.11.6
 - (Fabric only) Fabric API: 0.38.0

**Comment by VidTuGit** [comment] 2021-08-19 04:51
Yeah, I understood the problem. It's caused by JShell hacky code, that I'm using and it's missing in the *JRE* builds. I'll fix this in the next update.

As a temporary workaround, I suggest trying one of three methods
1. Delete your current AdoptOpenJDK and install AdoptOpenJDK HotSpot JDK. (**Unrecommended**, can cause PATH environment problems and other issues with your current Java installations)
2. Download OpenJDK [as an archive](https://jdk.java.net/16/), unpack it, and [point MultiMC](https://i.imgur.com/akPHqiB.png) to `bin/javaw.exe` in that unpacked archive.
3. If you have used 1.17(.1) in the original Minecraft Launcher [point MultiMC](https://i.imgur.com/akPHqiB.png) to their java-runtime-alpha in the Minecraft Launcher folder. (in my case, that's `C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\javaw.exe`)

**Comment by VidTuGit** [comment] 2021-08-25 00:16
Should be fixed in 7.1.1.

**Closed by VidTuGit** 2021-08-25 00:16 UTC
Labels: bug
