### ISSUE TITLE
Infinite world save screen

### ISSUE THREAD

**Issue by xMelonekMaX** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#147] opened 2024-05-04 12:52 UTC
After logging into my account, entering and exiting the singleplayer world, I am left with an infinite save screen

Quilt Loader 1.20.6
Mods:
- IAS-Quilt-1.20.6-9.0.0-beta.4.jar
- fabric-api-0.97.8+1.20.6.jar

**Comment by xMelonekMaX** [comment] 2024-05-13 14:29
I only noticed this behavior on the XMCL launcher

**Comment by xMelonekMaX** [comment] 2024-05-13 14:33
You need to log in to a premium account that wasn't logged in via the launcher, but via the mod to get this effect

**Comment by VidTu** [comment] 2024-05-16 12:36
unable to reproduce this issue on vanilla, multimc and prism launcher. as XMCL launcher refuses to be loaded (for some reason) on VMware or VirtualBox (the launcher itself, other launchers work fine and 3D/VGA driver virtualization for Minecraft works fine), i'll mark this as "won't fix", because i don't trust random launchers to be launched on my host pc. nevertheless, if the issue appears only with THAT specific launcher and only with it, you probably want to ask launcher developers about this

**Closed by VidTu** 2024-05-16 12:36 UTC
