### ISSUE TITLE
Reload Skins button in the way of alts

### ISSUE THREAD

**Issue by Kenshayy** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#37] opened 2021-08-10 15:15 UTC
As stated in the title, the Reload Skins button is in the way of the accounts names. You can still click it but it's kinda annoying. 
Screenshot:
![image](https://user-images.githubusercontent.com/20501996/128892940-dd66f165-9ab4-420d-ba8e-3d23131eb186.png)

**Comment by VidTuGit** [comment] 2021-08-10 17:55
Not a bug, but an annoyance. Occurs only on 1.12.2 or below. I will fix it in the next version.

(This is how it looks on 1.17)
![image](https://user-images.githubusercontent.com/60929459/128910317-05b17873-296a-4eb9-a366-e682fd6a98e7.png)

**Comment by Kenshayy** [comment] 2021-08-10 19:17
> Not a bug, but an annoyance. Occurs only on 1.12.2 or below. I will fix it in the next version.
> 
> (This is how it looks on 1.17)
> ![image](https://user-images.githubusercontent.com/60929459/128910317-05b17873-296a-4eb9-a366-e682fd6a98e7.png)

Oh thanks. Yea. I am on 1.8.9

**Comment by VidTuGit** [comment] 2021-08-25 00:19
Should be fixed in 7.1.1.

**Closed by VidTuGit** 2021-08-25 00:19 UTC
Labels: bug
