### ISSUE TITLE
what's this?

### ISSUE THREAD

**Issue by CapiFelix** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#54] opened 2022-03-31 15:41 UTC
**Describe the bug**
I can't connect to my microsoft account.
**To Reproduce**

![error](https://user-images.githubusercontent.com/80063302/161095194-e1a3c653-8976-44bc-92a3-d9d1095c5a7a.png)

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [e.g. 1.16.5]
 - Mod Version: [e.g. 7.1]
 - Loader type: [e.g. Fabric]
 - Loader version [e.g. 0.11.3]
 - (Fabric only) Fabric API: [e.g. Fabric API 0.19.0 build 398]

**Comment by VidTu** [comment] 2022-03-31 15:53
Duplicate of #53

**Closed by VidTu** 2022-03-31 15:53 UTC
Labels: bug, duplicate
