### ISSUE TITLE
Why can't I switch back to my main account from the IGAS?

### ISSUE THREAD

**Issue by KualaBear** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#26] opened 2021-05-16 01:12 UTC
I don't have really much to say but the fact that I can't switch back to my main from In-Game-Account-Switcher after switching to an alt is just impossible. Kinda sad about that. Let me know if I miss anything.

**Comment by 2xsaiko** [comment] 2021-05-16 06:53
I never designed it to use the session of the account that the game was originally started with, and I guess it was never changed. I just had my main account in the account list as well.

**Comment by VidTuGit** [comment] 2021-05-16 15:40
You can add this account as an alt as well.

**Comment by KualaBear** [comment] 2021-05-16 20:32
Well...I guess that would make sense just logging in with an alt

**Comment by VidTuGit** [comment] 2021-05-17 00:32
Relog allows logging into an account you're already logged in to. (since 7.0.6)
Switching to the main account does not make sense when you can add it as an alt.
If your report is a feature request, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=).
If you still think this is a bug, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=bug&template=bug-report.md&title=).
###### (Maybe I'll add switching to the main account in 7.1-pre2)

**Comment by KualaBear** [comment] 2021-05-17 00:43
> Relog allows logging into an account you're already logged in to. (since 7.0.6)
> Switching to the main account does not make sense when you can add it as an alt.
> If your report is a feature request, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=).
> If you still think this is a bug, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=bug&template=bug-report.md&title=).
> 
> ###### (Maybe I'll add switching to the main account in 7.1-pre2)

"Switching to main doesn't make sense when

**Comment by KualaBear** [comment] 2021-05-17 00:48
> Relog allows logging into an account you're already logged in to. (since 7.0.6)
> Switching to the main account does not make sense when you can add it as an alt.
> If your report is a feature request, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=).
> If you still think this is a bug, please use [this template](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/new?assignees=&labels=bug&template=bug-report.md&title=).
> 
> ###### (Maybe I'll add switching to the main account in 7.1-pre2)

"Switching to the main account does not make sense when you can add it as an alt" Are you talking about adding my main to the switch mod? If you were referring to that...well that somehow doesn't work for me idk why.
The reason why I want to switch between my alt and main is because I am using both for my own purposes. Since I have my main login at mc launcher and my alt add in switch. When Switching to alt and back to my main from switch mod it won't let me, saying something like "credential...".

Well I tried 2xsaiko instructions. Making my main and alt. Which that somehow doesn't work...it won't let me login from switch mod saying like "credential..."

**Comment by VidTuGit** [comment] 2021-05-17 01:35
Okay, did you enter your username or email into the "Username" field?

**Comment by KualaBear** [comment] 2021-05-17 01:37
> Okay, did you enter your nickname or account email into the "Username" field?

With all due respect and no mean. But I atleast have the knowledge of that

**Comment by VidTuGit** [comment] 2021-05-17 01:38
No, I'm asking what exactly did you enter there. Name or email? (Or you have tried both?)

**Comment by KualaBear** [comment] 2021-05-17 01:46
> No, I'm asking what you exactly entered there. Name or email? (Or you have tried both?)

I tried any possible solution I could think of.
Putting my username, email.
Only sign in with my alt from mc and sign in my main on the switch mod. Which doesn't work idk why. I tried with the older version which seems to work for awhile and it stopped working.
I feel it defeat the main purpose of account switcher if I couldn't switch back to my main after using my alt or to even use my alt as my mc launcher, because I would need to switch to my main every once in awhile if I would play on my own server.

**Comment by VidTuGit** [comment] 2021-05-17 02:08
Okay, if the issue is what I think, I'll fix it in 7.1-pre2.

**Comment by KualaBear** [comment] 2021-05-17 02:11
> Okay, if the issue is what I think, I'll fix it in 7.1-pre2.

Looking forward to any. Been using the mod for quiet a long time now and it serve me well so thankful for that.

**Comment by VidTu** [comment] 2022-08-24 12:26
All issues with accounts should be fixed in 8.0.0 and I'm not planning to store original username/UUID/accessToken, because you should be able to add your account into IAS now.

**Closed by VidTu** 2022-08-24 12:26 UTC
Labels: enhancement
