### ISSUE TITLE
My friend has this error when logging in to his premium account:

### ISSUE THREAD

**Issue by xMelonekMaX** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#149] opened 2024-05-15 16:51 UTC
[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/15324552/latest.log)
![image](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/assets/96833801/bb043883-86b5-4243-ad29-bfdc24b12ac2)

When he logs in, he is shown information about the login page and the code to use.

Quilt Loader 1.20.1
IAS 9.0.0-beta.4

**Comment by VidTu** [comment] 2024-05-16 12:38
unable to reproduce. it seems you have corrupted JAR (`Caused by: java.lang.RuntimeException: Failed to load class file for 'ru.vidtu.ias.utils.Holder'!`) and/or the mod JAR has been deleted while the game was running (`Caused by: java.nio.channels.ClosedByInterruptException`)

**Comment by VidTu** [comment] 2024-05-18 13:33
unable to reproduce

**Comment by melonkowymelonek** [comment] 2024-05-19 15:58
[latest (1).log](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/15369973/latest.1.log)
I guess it's the same mistake here. The file's hashcode matches the one downloaded from the website

**Comment by xMelonekMaX** [comment] 2024-05-19 15:58
I guess it's the same mistake here. The file's hashcode matches the one downloaded from the website
[latest (1).log](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/15369976/latest.1.log)

**Comment by VidTu** [comment] 2024-05-19 17:54
it looks like some sort of race-condition in the quilt loader itself (since not able to reproduce on fabric/forge), use `-Dloader.workaround.jar_copy_all_mods=true` JVM flag as a temporary workaround for now

**Comment by VidTu** [comment] 2024-05-19 21:17
related to https://github.com/QuiltMC/quilt-loader/issues/431.
fixed in 0a6a8b3b7fd3570f311cfdf994f1d8fd40129a48.
will be released in the future. (test builds can be downloaded [here](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/actions/runs/9150577237))

**Comment by VidTu** [comment] 2024-05-21 15:51
Fixed in 9.0.0-beta.5.

**Closed by VidTu** 2024-05-21 15:51 UTC

**Comment by xMelonekMaX** [comment] 2024-05-29 16:44
On 9.0.0-beta.5:
[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/files/15487732/latest.log)

**Comment by VidTu** [comment] 2024-05-29 17:54
no internet connection

**Comment by xMelonekMaX** [comment] 2024-05-30 13:39
https://youtu.be/Dwi65rV05PQ?si=Kk8vDzRzKeYcC4XR

This tutorial solved the problem. Is there a way to work around this problem as only Feather and IAS had this problem. Everything worked on Lunar Client all the time.

**Comment by VidTu** [comment] 2024-05-30 15:32
i would certainly neither install nor use the client that modifies my "hosts" file without BIG RED warning about it. it's like a malware. for what purpose should a minecraft launcher (or to be fair, any program, except those designed for software piracy, content blocking, or for parental/employee controls) should block my internet traffic?
